### ISSUE TITLE
Unspecified error as notification

### ISSUE THREAD

**Issue by habi** [DP-3T/dp3t-app-ios-ch#102]
Yesterday evening I got a notification about an error (screenshot below).
When opening the app from the notification I get no further messages and details about the error.

I'm using SwissCovid Version 1.02 installed on an iPhone SE (original) with iOS 13.5.5 (and am employed at the University of Bern).

<img width="320" alt="Screenshot 2020-06-10 at 23 23 39" src="https://user-images.githubusercontent.com/1651235/84364095-f4b05c00-abcf-11ea-99b9-6eca77b210ac.png">

**Comment by habi** [comment]
[I cannot find anything in the code](https://github.com/DP-3T/dp3t-app-ios-ch/search?q=%22to+correct+the+error%22&unscoped_q=%22to+correct+the+error%22) linking to the notification...

**Comment by 7thsonch** [comment]
I have also received this error message several times. I'm not using the TestFlight version of the app. I'm using an older version from GitHub that is not yet based on Apple's exposure notification API.

**Comment by UBaggeler** [comment]
The notification in the attached screenshot is/was shown 2 days after the last successful synchronization (for example because background tasks were not scheduled). The text has been updated in the meantime: `sync_warning_notification_title` and `sync_warning_notification_text`. See [TracingLocalPush.swift](https://github.com/DP-3T/dp3t-app-ios-ch/blob/master/DP3TApp/Logic/Tracing/TracingLocalPush.swift#L132-L149).
