### ISSUE TITLE
I keep getting fake keys instead of real ones

### ISSUE THREAD

**Issue by jorgejams88** [DP-3T/dp3t-app-ios-ch#191]
For debugging purposes, is it possible to force the EN API to get actulal keys instead of fake ones?

**Comment by UBaggeler** [comment]
Can you describe the steps you are doing so we can try to understand and reproduce this behaviour?

Do you have a provisioning profile with the `com.apple.developer.exposure-notification-test` entitlement? This way you should get the key of current day immediately (without waiting for it to be released on the next day). The EN framework does not release fake keys, the dp3t-sdk is filling up with fake-keys to make sure we always send out 14 keys (same payload size).

**Comment by jorgejams88** [comment]
Hi @UBaggeler 

Thanks for your response, I have the entitlement, this is the one we are using to test (it's the only option):

> Exposure Notification with Logging Support for xxxxxxx (Dev) iOS Dev

After some testing, we had to comment this line to be able to send keys that are not considered fake:

File: DP3TSDK/Sources/DP3TSDK/Cryptography/DiagnosisKeysProvider.swift
`filteredKeys = filteredKeys.filter { $0.date > onsetDate }`

Also:

We had to edit the following line

File: DP3TSDK/Sources/DP3TSDK/Networking/KnownCasesSynchronizer.swift
`guard descriptor.mode == .test || timingManager.shouldDetect(lastDetection: lastSync, now: now) else {`

changing it to:

`guard descriptor.mode == .production || timingManager.shouldDetect(lastDetection: lastSync, now: now) else {`

To get the other iPhone to download the keys from the server.

I suppose the change made in DiagnosisKeyProvider.swift should not be necessary after some days of using the app, because in that case the filter will not apply. But without commenting out those lines, what is the recommended way to test if everything is working correctly?

**Comment by UBaggeler** [comment]
Please try running the `Debug-Calibration` scheme, which uses the [Entitlements_Calibration.entitlements](https://github.com/DP-3T/dp3t-app-ios-ch/blob/master/DP3TApp/Supporting%20Files/Entitlements_Calibration.entitlements) file. This file contains the `com.apple.developer.exposure-notification-test` entitlement. Using this entitlement, EN will release the TEK of the current day (which is otherwise only released on the next day). Like this you will get at least one real day, even if the iPhone was restored/initialized today. This entitlement can only be used for debugging. Uploading an app with this entitlement to Testflight will fail.

**Comment by jorgejams88** [comment]
Thanks @UBaggeler now I know my problem.

It is very important to define the onset date correctly. In my case we were using the date the user was receiving their results as reference, ideally the date when the user is getting tested (maybe a couple of days earlier than that) is the date that should be used.
