### ISSUE TITLE
Exposure checks aren’t spread throughout the whole day

### ISSUE THREAD

**Issue by BorntraegerMarc** [DP-3T/dp3t-app-ios-ch#344]
I experience the same issue as https://github.com/corona-warn-app/cwa-server/issues/663

Here’s my exposure checks:
![228EAA8D-E646-4ECE-A53F-53AFEB80A420](https://user-images.githubusercontent.com/7549295/97103367-35ef6700-16ac-11eb-859b-fc4a654ee6b5.png)

I’ve been outside the whole day yesterday. I’m no expert, but it seems to me that having 10 checks exactly at 16:02 is not very helpful. Shouldn’t checks be spread through out the whole day?

The pattern I noticed yesterday is consistent for all days.

Using iOS 14.1 on a iPhone SE 2020

**Comment by BorntraegerMarc** [comment]
Reading through different issues in this project I understood that iOS exposure checks are limited. Isn’t it unfortunate if the limited exposure checks happen all at the same time instead of spread throughout 24 hours?

**Comment by BorntraegerMarc** [comment]
Same thing keeps happening... I wonder if anyone else could confirm this behavior?

I recently switched to iOS. I noticed the same behavior before on my android phone. But don’t have any screenshots to confirm/proof it.

![CEE8EDBA-6C75-4638-87B3-0ECAB63EFED7](https://user-images.githubusercontent.com/7549295/97781534-6b082780-1b8c-11eb-92bf-b7410dee32ca.png)
![F1AB65A4-D085-4B5F-8D2F-13E9516C4CC0](https://user-images.githubusercontent.com/7549295/97781535-6cd1eb00-1b8c-11eb-94ce-85aba4a66016.png)

**Comment by UBaggeler** [comment]
Transmitting and scanning for RPI's happens continuously in the background. What you are seeing in this screenshot are the exposure checks (syncing reported positive cases with locally collected/stored RPI's). Here are some more explanations:
- https://github.com/DP-3T/dp3t-sdk-ios/blob/1.3.0/EXPOSURE_NOTIFICATION_API_USAGE.md
- https://github.com/DP-3T/dp3t-app-ios-ch/issues/249#issuecomment-681951107

Due to limitations of the first version of the ExposureNotification API, SwissCovid is grouping TEK's per day and checking/syncing the past 10 days separately. With a rate limit of 20 calls per 24h, this means we can check/sync twice per day (2 x 10 days). 

With ENv2 (version 2 of the ExposureNotification.framework) we do not need to group by day anymore and can now spread these checks throughout the day. This is currently being released (phased) in SwissCovid 1.2. After updating the app, you will then see a check/sync every 4h (rate limit is now 6 per 24h). We also updated the [EXPOSURE_NOTIFICATION_API_USAGE](https://github.com/DP-3T/dp3t-sdk-ios/blob/develop/EXPOSURE_NOTIFICATION_API_USAGE.md) document to reflect this.

Does this answer your question?

**Comment by BorntraegerMarc** [comment]
It does answer my question! Also it calms me to know that exposures are not only checked once per day 🙂 thx a lot!
